# config.yaml
common:
  log_level: info
  log_format: structured
tools:
  packages:
    purge:
      operation: repo-packages-purge
      with:
        owner: my-org
        package: my-image
        owner_type: org
        token_source: env:GITHUB_PACKAGES_TOKEN
        page_size: 50
  reports:
    audit:
      operation: audit-report
      with:
        output: ./audit.csv
workflow_tools:
  - name: conversion.default
    operation: convert-protocol
    with:
      from: https
      to: git
  - name: rename.clean
    operation: rename-directories
    with:
      require_clean: true
  - name: migration.legacy
    operation: migrate-branch
    with:
      targets:
        - remote_name: origin
          source_branch: main
          target_branch: master
          push_to_remote: true
          delete_source_branch: false
  - name: audit.weekly
    operation: audit-report
    with:
      output: ./reports/audit.csv
workflow:
  - with:
      tool_ref: conversion.default
  - operation: update-canonical-remote
  - with:
      tool_ref: rename.clean
  - with:
      tool_ref: migration.legacy
  - with:
      tool_ref: audit.weekly
      output: ./reports/audit-latest.csv
