# config.yaml
common:
  log_level: info
  log_format: structured
tools:
  packages:
    purge:
      operation: repo-packages-purge
      with:
        owner: my-org
        package: my-image
        owner_type: org
        token_source: env:GITHUB_PACKAGES_TOKEN
        page_size: 50
  reports:
    audit:
      operation: audit-report
      with:
        output: ./audit.csv
operations:
  - &conversion_default
    operation: convert-protocol
    with: &conversion_default_options
      from: https
      to: git
  - &rename_clean
    operation: rename-directories
    with:
      require_clean: true
  - &migration_legacy
    operation: migrate-branch
    with:
      targets:
        - remote_name: origin
          source_branch: main
          target_branch: master
          push_to_remote: true
          delete_source_branch: false
  - &audit_weekly
    operation: audit-report
    with: &audit_weekly_options
      output: ./reports/audit.csv
workflow:
  - <<: *conversion_default
  - operation: update-canonical-remote
  - <<: *rename_clean
  - <<: *migration_legacy
  - <<: *audit_weekly
    with:
      <<: *audit_weekly_options
      output: ./reports/audit-latest.csv
