# config.yaml
common:
  log_level: info
  log_format: structured

tools:
  audit:
    roots:
      - ~/Development
    debug: false

  branch_cleanup:
    remote: origin
    limit: 100
    dry_run: false
    roots:
      - ~/Development

  migrate:
    dry_run: false
    debug: false

  packages:
    purge:
      owner: my-org
      package: my-image
      owner_type: org
      token_source: env:GITHUB_PACKAGES_TOKEN
      page_size: 50

  repos:
    rename:
      dry_run: false
      assume_yes: true
      require_clean: true
      roots:
        - ~/Development
    remotes:
      dry_run: false
      assume_yes: true
      roots:
        - ~/Development
    protocol: &workflow_convert_protocol_options
      dry_run: false
      assume_yes: true
      roots:
        - ~/Development
      from: https
      to: git

  workflow:
    roots:
      - ~/Development
    dry_run: false
    assume_yes: false
    steps:
      convert_protocol: &workflow_convert_protocol_step
        operation: convert-protocol
        with:
          from: https
          to: git
      update_canonical_remote: &workflow_update_canonical_remote_step
        operation: update-canonical-remote
      rename_directories: &workflow_rename_directories_step
        operation: rename-directories
        with:
          require_clean: true
      migrate_branch: &workflow_migrate_branch_step
        operation: migrate-branch
        with:
          targets:
            - remote_name: origin
              source_branch: main
              target_branch: master
              push_to_remote: true
              delete_source_branch: false
      audit_report: &workflow_audit_report_step
        operation: audit-report
        with: &workflow_audit_report_options
          output: ./reports/audit.csv

workflow:
  - *workflow_convert_protocol_step
  - *workflow_update_canonical_remote_step
  - *workflow_rename_directories_step
  - *workflow_migrate_branch_step
  - <<: *workflow_audit_report_step
    with:
      <<: *workflow_audit_report_options
      output: ./reports/audit-latest.csv
