# config.yaml
common:
  log_level: info
  log_format: structured

operations:
  - &audit_defaults
    operation: audit
    with:
      roots:
        - ~/Development
      debug: false

  - &packages_purge_defaults
    operation: repo-packages-purge
    with:
      package: my-image

  - &branch_cleanup_defaults
    operation: repo-prs-purge
    with:
      remote: origin
      limit: 100
      dry_run: false
      roots:
        - ~/Development

  - &repo_remotes_defaults
    operation: repo-remote-update
    with:
      dry_run: false
      assume_yes: true
      roots:
        - ~/Development

  - &repo_protocol_defaults
    operation: repo-protocol-convert
    with:
      dry_run: false
      assume_yes: true
      roots:
        - ~/Development
      from: https
      to: git

  - &repo_rename_defaults
    operation: repo-folders-rename
    with:
      dry_run: false
      assume_yes: true
      require_clean: true
      roots:
        - ~/Development

  - &workflow_command_defaults
    operation: workflow
    with:
      roots:
        - ~/Development
      dry_run: false
      assume_yes: false

  - &branch_migrate_defaults
    operation: branch-migrate
    with:
      debug: false
      roots:
        - ~/Development

  - &convert_protocol_step
    operation: convert-protocol
    with:
      from: https
      to: git

  - &canonical_remote_step
    operation: update-canonical-remote

  - &rename_directories_step
    operation: rename-directories
    with:
      require_clean: true

  - &migrate_branch_step
    operation: migrate-branch
    with:
      targets:
        - remote_name: origin
          source_branch: main
          target_branch: master
          push_to_remote: true
          delete_source_branch: false

  - &audit_report_step
    operation: audit-report
    with:
      output: ./reports/audit.csv

workflow:
  - step:
      order: 1
      <<: *convert_protocol_step

  - step:
      order: 2
      <<: *canonical_remote_step

  - step:
      order: 3
      <<: *rename_directories_step

  - step:
      order: 4
      <<: *migrate_branch_step

  - step:
      order: 5
      <<: *audit_report_step
      with:
        output: ./reports/audit-latest.csv
