# workflow.yaml
steps:
  - operation: convert-protocol
    with:
      from: https
      to: git
  - operation: update-canonical-remote
  - operation: rename-directories
    with:
      require_clean: true
  - operation: migrate-branch
    with:
      targets:
        - remote_name: origin
          source_branch: main
          target_branch: master
          push_to_remote: true
          delete_source_branch: false
  - operation: audit-report
    with:
      output: ./audit.csv