common:
  log_level: info
  log_format: console
  dry_run: false
  assume_yes: false
  require_clean: false

operations:
  - operation: audit
    with:
      roots:
        - .
  - operation: repo-packages-purge
    with:
      roots:
        - .
  - operation: repo-prs-purge
    with:
      remote: origin
      limit: 100
      roots:
        - .
  - operation: repo-remote-update
    with:
      roots:
        - .
  - operation: repo-protocol-convert
    with:
      roots:
        - .
  - operation: repo-folders-rename
    with:
      roots:
        - .
      include_owner: false
  - operation: workflow
    with:
      roots:
        - .
  - operation: branch-migrate
    with:
      roots:
        - .
