common:
  log_level: error
  log_format: console
  dry_run: false
  assume_yes: false
  require_clean: false

operations:
  - operation: audit
    with:
      roots:
        - .
  - operation: repo-packages-purge
    with:
      roots:
        - .
  - operation: repo-prs-purge
    with:
      remote: origin
      limit: 100
      roots:
        - .
  - operation: repo-remote-update
    with:
      roots:
        - .
      owner: ""
  - operation: repo-protocol-convert
    with:
      roots:
        - .
  - operation: repo-folders-rename
    with:
      roots:
        - .
      include_owner: false
  - operation: repo-release
    with:
      roots:
        - .
      remote: origin
  - operation: workflow
    with:
      roots:
        - .
  - operation: branch-refresh
    with:
      roots:
        - .
  - operation: branch-default
    with:
      roots:
        - .
  - operation: branch-cd
    with:
      roots:
        - .
      remote: origin
      branch: master
  - operation: commit-message
    with:
      roots:
        - .
      api_key_env: OPENAI_API_KEY
      model: gpt-4.1-mini
      diff_source: staged
      max_completion_tokens: 256
      temperature: 0.2
      timeout_seconds: 60
  - operation: changelog-message
    with:
      roots:
        - .
      api_key_env: OPENAI_API_KEY
      model: gpt-4.1-mini
      max_completion_tokens: 1200
      temperature: 0.3
      timeout_seconds: 60
