name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: CheckoutCode
        uses: actions/checkout@v4

      - name: SetupGoEnvironment
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: BuildCTXBinaries
        run: |
          mkdir -p dist
          GOOS=linux   GOARCH=amd64   go build -ldflags="-s -w" -o dist/ctx_linux_amd64   ./cmd/ctx
          GOOS=darwin  GOARCH=amd64   go build -ldflags="-s -w" -o dist/ctx_darwin_amd64  ./cmd/ctx
          GOOS=darwin  GOARCH=arm64   go build -ldflags="-s -w" -o dist/ctx_darwin_arm64 ./cmd/ctx
          GOOS=windows GOARCH=amd64   go build -ldflags="-s -w" -o dist/ctx_windows_amd64.exe ./cmd/ctx

      - name: GenerateChecksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: ExtractReleaseNotes
        run: |
          TAG_NAME=${{ github.ref_name }}
          sed -n "/## \[$TAG_NAME\]/,/\(## \[v[0-9]\)/p" CHANGELOG.md | grep -v '^## \[' > release_notes.md

      - name: CreateGitHubRelease
        uses: softprops/action-gh-release@v2
        with:
          name: "CTX release ${{ github.ref_name }}"
          body_path: release_notes.md
          files: |
            dist/ctx_linux_amd64
            dist/ctx_darwin_amd64
            dist/ctx_darwin_arm64
            dist/ctx_windows_amd64.exe
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}